/**
 * @author Vikash Sharma <vikashsharma2039@gmail.com>
 * @file output
 * @description Bundle writer — produces the `enhanced-<name>/` folder that
 *   ships with every skill-enhance run. Per SPEC Q5.
 * @see SPEC.md §"Locked Decisions Q5"
 */

import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { writeRunsHeader, type RunRecord, type RunsHeader } from "../eval/runs-io.js";
import type { ScoreAggregate } from "../eval/types.js";

export interface BundleContext {
  /** Display-friendly name (e.g. "code-summarizer"). */
  name: string;
  /** Output directory (e.g. `./enhanced-code-summarizer`). Created if missing. */
  outDir: string;
  /** Initial skill text (v0). */
  v0Text: string;
  /** Best skill text (last accepted). */
  bestText: string;
  /** Initial aggregate (after v0 was scored). */
  v0Aggregate: ScoreAggregate;
  /** Best aggregate (after last accepted iter — or equal to v0 if none accepted). */
  bestAggregate: ScoreAggregate;
  /** All run records, in iteration order. */
  records: RunRecord[];
  /** cases.json sha256 frozen at run start. */
  casesSha256: string;
  /** v0 skill sha256 at run start. */
  v0Sha256: string;
  /** Provider + model used. */
  provider: string;
  model: string;
  /** Started-at ISO timestamp. */
  startedAt: string;
  /** cases.json content (raw bytes from disk) — preserves original. */
  casesJson: string;
  /** rubric.json content as a string. */
  rubricJson: string;
}

/**
 * Write the full bundle directory.
 *
 * Layout:
 *   <outDir>/
 *     SKILL.md           # best text (or v0 if no iter accepted)
 *     README.md          # human-readable changelog
 *     eval/
 *       cases.json       # frozen copy of input
 *       rubric.json      # axis definitions + weights
 *       runs.jsonl       # append-only iter history
 *       scores.tsv       # per-iter composite + per-axis
 *
 * @param ctx All data the bundle needs. Pure I/O; no LLM call.
 */
export async function writeBundle(ctx: BundleContext): Promise<void> {
  await mkdir(ctx.outDir, { recursive: true });
  await mkdir(join(ctx.outDir, "eval"), { recursive: true });

  // 1. SKILL.md — best-or-v0
  await writeFile(join(ctx.outDir, "SKILL.md"), ctx.bestText, "utf8");

  // 2. eval/cases.json — verbatim copy of input cases
  await writeFile(join(ctx.outDir, "eval", "cases.json"), ctx.casesJson, "utf8");

  // 3. eval/rubric.json — what the judge scored against
  await writeFile(join(ctx.outDir, "eval", "rubric.json"), ctx.rubricJson, "utf8");

  // 4. eval/runs.jsonl — header + all records
  await writeRunsHeader(join(ctx.outDir, "eval", "runs.jsonl"), {
    startedAt: ctx.startedAt,
    casesSha256: ctx.casesSha256,
    v0Sha256: ctx.v0Sha256,
    provider: ctx.provider,
    model: ctx.model,
  });
  for (const rec of ctx.records) {
    await writeRunsHeader; // no-op alias retained for tree-shake safety; actual append below
    await (await import("../eval/runs-io.js")).appendRun(
      join(ctx.outDir, "eval", "runs.jsonl"),
      rec,
    );
  }

  // 5. eval/scores.tsv — human-readable per-iter table
  const tsvHeader = [
    "iter",
    "mode",
    "kept",
    "composite",
    "correctness",
    "triggerFidelity",
    "outputQuality",
    "robustness",
    "reusability",
    "durationMs",
  ].join("\t");
  const tsvRows = ctx.records.map((r) =>
    [
      r.iter,
      r.mode,
      r.kept ? "1" : "0",
      r.composite.toFixed(2),
      r.axes.correctness!.toFixed(1),
      r.axes.triggerFidelity!.toFixed(1),
      r.axes.outputQuality!.toFixed(1),
      r.axes.robustness!.toFixed(1),
      r.axes.reusability!.toFixed(1),
      r.durationMs,
    ].join("\t"),
  );
  await writeFile(
    join(ctx.outDir, "eval", "scores.tsv"),
    [tsvHeader, ...tsvRows].join("\n") + "\n",
    "utf8",
  );

  // 6. README.md — human-friendly changelog
  const v0Comp = ctx.v0Aggregate.composite.toFixed(2);
  const bestComp = ctx.bestAggregate.composite.toFixed(2);
  const delta = (ctx.bestAggregate.composite - ctx.v0Aggregate.composite).toFixed(2);
  const acceptedCount = ctx.records.filter((r) => r.kept).length;
  const rejectedCount = ctx.records.length - acceptedCount;
  const wasMastery = ctx.records.some(
    (r) => r.kept && r.composite >= 9.5,
  );

  const v0AxisLines = ([
    "correctness",
    "triggerFidelity",
    "outputQuality",
    "robustness",
    "reusability",
  ] as const)
    .map(
      (k) =>
        `- ${k}: v0 ${ctx.v0Aggregate.axes[k]!.toFixed(2)} → best ${ctx.bestAggregate.axes[k]!.toFixed(2)}`,
    )
    .join("\n");

  const readme = `# Enhanced skill: ${ctx.name}

> Generated by \`skillenhance\` v0.1.0 on ${ctx.startedAt}.

## Score

| Iteration | Composite | Δ vs v0 |
| --- | --- | --- |
| v0 (baseline) | ${v0Comp} | — |
| Best | ${bestComp} | ${delta.startsWith("-") ? delta : "+" + delta} |

Mastery reached: **${wasMastery ? "YES" : "NO"}** (composite ≥ 9.5 + every axis ≥ 9.0).

Total iterations: **${ctx.records.length}** (accepted: ${acceptedCount}, discarded: ${rejectedCount})

## Per-axis progression

${v0AxisLines}

## Layout

- \`SKILL.md\` — the best-known version of the skill (or v0 if no iter accepted).
- \`eval/cases.json\` — frozen test cases (immutable during the run).
- \`eval/rubric.json\` — rubric axes + weights the judge scored against.
- \`eval/runs.jsonl\` — append-only NDJSON, one record per iteration.
- \`eval/scores.tsv\` — per-iter composite + per-axis in tab-separated form.

## Reproducing

\`\`\`sh
# from the input skill + cases
skillenhance enhance --skill <input-skill.md> --cases eval/cases.json --out .
\`\`\`

Provider: \`${ctx.provider}\` · Model: \`${ctx.model}\`
`;

  await writeFile(join(ctx.outDir, "README.md"), readme, "utf8");
}
